"""
Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""
prev, now, sums, next_no = 1, 2, 2, 0
while next_no < 4000000:
    next_no = prev + now
    prev = now
    now = next_no
    if next_no%2 == 0:
        sums = sums + next_no
print(sums)